# Custom Position Scissor Configuration
# For hardware with specific open/close positions

hardware:
  joint_name: "scissor_joint"
  position_limits:
    min_position: -3.14
    max_position: 0.50
  position_mapping:
    open_is_max: true
    custom_open_position: 0.3   # Custom open position
    custom_close_position: -2.0 # Custom close position

control:
  position_increment: 0.05
  min_command_interval: 0.05
  trajectory:
    default_duration: 0.3
    full_motion_duration: 1.0
    emergency_duration: 0.5

safety:
  max_effort: 1.2
  safety_open_distance: 0.15
  safety_cooldown: 2.0
  effort_normal_threshold: 0.8